const data = [
    {
        projectName: 'Tour-X',
        description1: 'This web site is about a tourism agency . Visitors can See details and Also order booking places.',
        description2: ' Fully Responsive UI with Authentication based Private Route website.',
        item1: 'HTML',
        item2: 'CSS3',
        item3: 'Bootstrap',
        item4: 'Material UI',
        item5: 'ReactJs',
        item6: 'NodeJs',
        item7: 'Firebase',
        item8: 'MongoDB',
        item9: 'React Router Dom',
        item10: 'Heroku',
        clientLink: 'https://github.com/mdriyajulkabir/Tour-X-Cleint',
        serverLink: 'https://github.com/mdriyajulkabir/Tour-X-Server',
        liveSite: 'https://tourx-64172.web.app/',
        mokeUpImg: 'https://i.postimg.cc/jD8fZ0sk/TourX.png'
    },
    {
        projectName: 'Support Life',
        description1: 'This web site is about a tourism agency . Visitors can See details and Also order booking places.',
        description2: ' Fully Responsive UI with Authentication based Private Route website.',
        item1: 'HTML',
        item2: 'CSS3',
        item3: 'Bootstrap',
        item4: '',
        item5: 'ReactJs',
        item6: 'NodeJs',
        item7: 'Firebase',
        item8: 'MongoDB',
        item9: 'React Router Dom',
        item10: 'Netlify',
        clientLink: 'https://github.com/mdriyajulkabir/Health-Care',
        serverLink: '',
        liveSite: 'https://friendly-beaver-bf7136.netlify.app/',
        mokeUpImg: 'https://i.postimg.cc/94mtPzM3/Support-Life.png'
    },
    {
        projectName: "Men's Suits",
        description1: 'This Talk About A Men’s Suits E-commerce . A MERN Stack Project.',
        description2: 'An admin can control the overall website. Admin can manage all orders,make any one admin, add items etc',
        item1: 'HTML',
        item2: 'CSS3',
        item3: 'Bootstrap',
        item4: 'Material UI',
        item5: 'ReactJs',
        item6: 'NodeJs',
        item7: 'Firebase',
        item8: 'MongoDB',
        item9: 'React Router Dom',
        item10: 'Heroku',
        clientLink: 'https://github.com/mdriyajulkabir/Mens-Suits-Client',
        serverLink: 'https://github.com/mdriyajulkabir/Men-s-Suits-Server',
        liveSite: 'https://mens-suits-d8a9b.web.app/',
        mokeUpImg: 'https://i.postimg.cc/bSZsqfwF/Mens-Suits.png'
    },
]